baseurl = "http://www.golangbelgrade.org/"
languageCode = "en-us"
title = "Golang Belgrade"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
theme = "angels-ladder"
canonifyurls = true

categories = [
  "news",
  "events"
]

[params]
  Author = "Golang Belgrade Team"
  Subtitle = "Golang Belgrade meetup group"
  Github = "GolangBelgrade"
  Twitter = "GolangBelgrade"
  GoogleAnalyticsUserID = "UA-71097558-1"
  Facebook = "golangbelgrade"
  ShowRelatedPost = true
  Summary = true  # takes true or false
  Content = false  # takes true or false
  SyntaxHighlightTheme = "github.min.css"
  # if both are set to true, summary is shown.
